### ISSUE TITLE
Streams not accessible to be stopped after using the component

### ISSUE THREAD

**Issue by victorfunes** [apivideo/api.video-typescript-media-stream-composer#9]
After using the component, not all the streams seem to be accessible to be stopped, leaving consumption of resources.
As you can see in your example application, if you add and remove streams, after removing all of them, in the navigator it is still showing the "warning with speakers / camera" of multimedia usage (this application is still using audio or video).
At least this is what happens to me in Google Chrome.

It would be useful to provide a functionality to allow to access to all the streams from outside to enable the disposal of resources after using the component. Now there is getStreams(), but drawingStream is not returned.

I would say the stream which is not accessible and still alive is the drawingStream created in the function createDrawingStream, but I don't know if there could be other in the merger as well.

**Comment by olivierapivideo** [comment]
Hi Victor,
In fact, closing the drawingStream will not be enough to make the browser warning disappear. 
We plan to add a destroy() method that will clean up everything. Would this meet your needs?

**Comment by victorfunes** [comment]
This would be perfect! Thank you!

**Comment by olivierapivideo** [comment]
@victorfunes we've released a new version (0.1.7) that contains the destroy() method.
